### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by pygabc1** [axium/Blind-Image-Deconvolution-using-Deep-Generative-Priors#3]
Hi, the folder of model_weights contains the files of celeba.h5, shoes.h5, and svhn.h5.
How to generate this files? 
Does this code contain to generate this file?
The paper says 
[trained on thousands of image examples, the weights of the untrained generator are learned on one blurred image y only in the deblurring process itself], 
but I still don't know how to generate these weights file when I use different data. 
Thanks.

**Comment by fahadshamshad** [comment]
If you are using your own dataset, you have to train the GAN model by yourself and save the weights of the generator in folder model_weights.
